
services:

  postgres:
    image: postgres:15
    container_name: mintic_postgres
    restart: always
    environment:
      POSTGRES_DB: mintic_db
      POSTGRES_USER: mintic_user
      POSTGRES_PASSWORD: mintic2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/3_datatransform/ddl:/docker-entrypoint-initdb.d
    networks:
      - mintic_net

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: mintic_jupyter
    restart: always
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "mintic2026"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: mintic_db
      POSTGRES_USER: mintic_user
      POSTGRES_PASSWORD: mintic2026
    volumes:
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
      - ./.env:/home/jovyan/.env
    depends_on:
      - postgres
    networks:
      - mintic_net

  adminer:
    image: adminer:latest
    container_name: mintic_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - mintic_net

volumes:
  postgres_data:

networks:
  mintic_net:
    driver: bridge