version: '3.8'

services:
  postgres_mia:
    image: postgres:15
    container_name: alexander_postgres
    restart: always
    environment:
      POSTGRES_DB: mintic_db
      POSTGRES_USER: mintic_user
      POSTGRES_PASSWORD: mintic2026
    ports:
      - "5433:5432" # USAMOS EL PUERTO 5433 PARA QUE NO CHOQUE CON TU COMPAÑERO
    volumes:
      - alex_postgres_data:/var/lib/postgresql/data
      # Esto cargará tus tablas automáticamente al iniciar
      - ./src/3_datatransform/ddl:/docker-entrypoint-initdb.d

networks:
  alex_net:
    driver: bridge

volumes:
  alex_postgres_data: